### ISSUE TITLE
api seems offline

### ISSUE THREAD

**Issue by KoenTech** [vicgalle/gpt-j-api#20]
When I try to access the API I get the following error: `ERR_CONNECTION_TIMED_OUT`. But when I try to connect to it using a different IP address it does work. Am I IP banned?

**Comment by maximignatev** [comment]
same

when making request from my serverless function deployed to vercel - i receive an error

when doing it local - all fine

**Comment by maximignatev** [comment]
btw is there other alternatives to https://sites.research.google/trc/ where i can launch an instance?

i left my requests there multiple times but no answer

**Comment by vicgalle** [comment]
Hi @KoenTech @maximignatev 

The server implements some form of load balancing by banning IPs whose queries to the API seem to come from spam bots, which congested the whole API for all users. Since they can change IP, it can also ban entire subnetworks.

If you believe your IP has been unfairly banned, please email me with the IP so I can have a look

**Comment by vicgalle** [comment]
> btw is there other alternatives to https://sites.research.google/trc/ where i can launch an instance?
> 
> i left my requests there multiple times but no answer

By free alternatives, that's the only one, sorry. If you include paid alternatives, you could use a GPU from AWS, but the inference speed is gonna be slower
