### ISSUE TITLE
Raw text...

### ISSUE THREAD

**Issue by Vilagamer999** [vicgalle/gpt-j-api#39]
This is probably a very stupid question but whenever I run GPT-J I always get the full output:

`{'model': 'GPT-J-6B', 'compute_time': 1.2492187023162842, 'text': ' \n(and you\'ll be a slave)\n\n**_"I\'m not a robot, I\'m a human being."_**\n\n**_"I\'m not a robot, I\'m a human being."_**\n\n', 'prompt': 'AI will take over the world ', 'token_max_length': 50, 'temperature': 0.09, 'top_p': 0.9, 'stop_sequence': None}`

What parameter do I need to change so it only outputs the generated text?

`(and you'll be a slave)
I'm not a robot, I'm a human being. I'm not a robot, I'm a human being.`

**Comment by SafaTinaztepe** [comment]
You can modify the code to just return the text output [here](https://github.com/vicgalle/gpt-j-api/blob/7f78623ca3d4f9554ab85324113df8c84669553f/serve.py#L97)

Instead of building the entire response object at the end of the generate function, just say `return text` and you're done, if that's what you're trying to achieve.
